# Generated by Django 3.1.1 on 2020-09-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Lord', 'Lord'), ('Lady', 'Lady')], default='', max_length=60),
        ),
    ]
