# Generated by Django 3.1.1 on 2020-09-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200906_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='type',
            new_name='Type',
        ),
    ]
